# Generated by Django 2.2.9 on 2022-06-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='customer',
            table='TB_CUSTOMER_2',
        ),
    ]
