# Generated by Django 2.2.9 on 2022-06-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220605_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='sobrenome',
        ),
    ]
