# Generated by Django 2.2.9 on 2022-06-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10)),
                ('kind', models.IntegerField(choices=[(1, 'Moto'), (2, 'Carro')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
            options={
                'db_table': 'TB_CUSTOMER_VEHICLES',
            },
        ),
    ]
